### ISSUE TITLE
谢谢分享，我们的配置大概一样诶。

### ISSUE THREAD

**Issue by Baojun-Chen** [aahowe/ROG-B460i_Hackintosh_OpenCore_EFI#1]
1.我也是这个主板，这个主板能网卡能换BCM 94352Z网卡吗？
2.cpu10700
3.讯景的r9 nano （有啸叫很烦）

我这配置用这个EFI应该问题不大吧。

**Comment by aahowe** [comment]
主板网卡拆开就可以换，问题不大
