### ISSUE TITLE
开启BIOS写保护会让macos变卡

### ISSUE THREAD

**Issue by doubleHon** [aahowe/ROG-B460i_Hackintosh_OpenCore_EFI#3]
首先十分感谢大佬提供的efi让我吃上Monterey的🍎，但是按照教程里面写的如果开启了BIOS写保护的话，打开MacOS系统会变卡，目前没有测试睡眠是否正常，但并不影响使用，目前有个小问题就是不操作键鼠，屏幕很快就熄屏了，不知道啥原因，不知道大佬有没有这个问题，如果可以解决的话就更好了，十分感谢

**Comment by aahowe** [comment]
bios需要关闭CFG Lock的，不操作键鼠息屏你看看`设置-节能`里是不是打开了自动关闭显示器，我这里没有这种情况

**Comment by doubleHon** [comment]
Thanks，貌似我也关闭CFG Lock了，但现在不影响我的一些操作，略微有些瑕疵也可以接受，我将你的efi更新到了0.8.0，以及切换了官方的主题，准备发布到github
