### ISSUE TITLE
OCS

### ISSUE THREAD

**Issue by lovenobugs** [aahowe/ROG-B460i_Hackintosh_OpenCore_EFI#4]
OCS: No schema for AllowNvramReset at 0 index, context ‹Security>
OCS: No schema for AllowToggleSip at 2 index, context (Security> !
请问启动时出现这两个提示，要怎么解决

**Comment by aahowe** [comment]
用0.8.2版本的ocvalidate工具检测一下config.plist试试

**Comment by lovenobugs** [comment]
用ocat工具升级&重新保存了一下就好了，谢谢
