### ISSUE TITLE
需要互联网连接才能安装macos

### ISSUE THREAD

**Issue by saint0hu** [aahowe/ROG-B460i_Hackintosh_OpenCore_EFI#5]
这是恢复盘进行的？

**Comment by aahowe** [comment]
不需要联网啊，黑果小兵下载一个镜像刷入刷入u盘，把efi分区替换为本项目就行了

**Comment by saint0hu** [comment]
我是按照OpenCore里面的来的，下载Monterey 12的BaseSystem.chunklist和BaseSystem.dmg放入了u盘里，使用了你efi，三码也换了，出来的却是重新安装 macos
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aahowe/ROG-B460i_Hackintosh_OpenCore_EFI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月7日(星期天) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aahowe/ROG-B460i_Hackintosh_OpenCore_EFI] 需要互联网连接才能安装macos (Issue #5)





 
不需要联网啊，黑果小兵下载一个镜像刷入刷入u盘，把efi分区替换为本项目就行了

**Comment by aahowe** [comment]
我没有试过opencore提供的安装方法，无法回答你的问题
